### ISSUE TITLE
cant click on item in table view when then page list doesnt fill the screen

### ISSUE THREAD

**Issue by eclair4151** [pronebird/UIScrollView-InfiniteScroll#39] opened 2016-06-28 19:04 UTC
If you have a collection view or table view with only like 3 items in it, if you scroll down just a little bit and there are no more items the loader dismisses but doesn't fully scroll back to the top. Then after that clicking on an item just tries to load more items and doesn't let you click it until you pull down manually. see attached video

https://drive.google.com/open?id=0B4kg_oK02hFPd3M0YjRma2ZJNjQ

**Comment by pronebird** [comment] 2016-06-28 21:38
Hi,

Thanks for reporting this, however I am not able to reproduce the described issue. The commit from above and branch `issue/39` attempts to reproduce the case when only 3 items are allowed to be in collection view. Bounce back seems to work fine after loading completed and no more items added into collection view.

At this point it's really hard to tell what goes wrong. It would be great if you could provide a demo app that reproduces this issue. 

Apart from that, if you use custom collection view layout, make sure that you properly calculate content size.

Cheers,
Andrej

**Comment by eclair4151** [comment] 2016-06-28 21:48
Ill try to upload an example today with a repro. its not just collections views my uitable view does the same thing. Try this.
Its a regular tableview not a tableviewcontroller. nothing special except Custom Prototype cells and have like 3 cells. then in the addinfinitescrollwithhandler immediately call tableview.finishInfiniteScroll(). Then on the phone barely scrolldown so its like half way into scrollwheel and let go. after that i cant click on a cell

**Comment by eclair4151** [comment] 2016-06-28 22:59
@pronebird here is the repro

https://github.com/eclair4151/infiniteScrollBug/tree/master/InfiniteScrollBug

**Comment by pronebird** [comment] 2016-06-28 23:33
Still can't reproduce it. I checked on iOS 9.3 on iPhone and in simulator. All cells seem to be pretty tappable after infinite scroll indicator appears / disappears. Are you sure there is nothing else in your project that may conflict with scroll views? Maybe any other categories?

**Comment by eclair4151** [comment] 2016-06-28 23:45
did you check my repo? its a completely empty project i created 30 min ago with 1 table view in it. if you run that project and just scroll down very slowly and a tiny bit it still works for you in my project?

**Comment by eclair4151** [comment] 2016-06-28 23:48
in addition the 0.9.0 one has this weird bug where if its not full when the end animation finishes the spinner glitches out and transports to below the bottom cell and then animates down away, which didnt happen in 0.8.0

**Comment by pronebird** [comment] 2016-06-28 23:53
Oh I see what you mean. Yeah the scroll gets stuck in between if you scroll slowly and it leave half way through. I had a check for that but it's apparently wrong.

I just addressed the glitch with spinner's teleportation below last cell in 95cd8d7e5f4f16da7d40fc80ee4edcf8ebb876e2

**Comment by pronebird** [comment] 2016-06-30 00:39
`develop` branch should have a fix. I am not entirely happy with it because even though I fixed the bounce back, spinner disappears too early/abrupty in certain cases, ideally it should slide down then disappear. 

Let me know if that patch makes problem go away.

**Comment by pronebird** [comment] 2016-07-03 16:33
Should be fixed in 0.9.1. Please check and re-open if this issue comes back. Thank you for raising this issue.

**Closed by pronebird** 2016-07-03 16:33 UTC
Labels: bug, need-testing
