### ISSUE TITLE
runtime crash - nsexception

### ISSUE THREAD

**Issue by heyalexchoi** [pronebird/UIScrollView-InfiniteScroll#80] opened 2019-02-23 02:02 UTC
i get a crash using just the example code:
```
tableView.addInfiniteScroll { (tableView) -> Void in
            // finish infinite scroll animation
            tableView.finishInfiniteScroll()
        }
```
nothing informative in the trace - just an exception of type `NSException` - thrown basically as soon as this code gets called in `viewDidLoad`.

xcode 10.1
iphone simulator iphone 7 + 8
real iphone 9

sorry i don't have any more useful information.

**Comment by pronebird** [comment] 2019-02-23 09:58
Hi,

iOS 12.1 right?

**Comment by heyalexchoi** [comment] 2019-02-23 16:37
I think so but tbh I found an already integrated dependency has the
functionality I need.

**Comment by pronebird** [comment] 2019-02-23 16:40
Alright cool. I couldn't reproduce the crash on my end, so I will close this issue. If you wish to get to the bottom of this, please attach the call stack or at least what kind of NSException you have got.

**Closed by pronebird** 2019-02-23 16:40 UTC
