### ISSUE TITLE
Activity Indicator hides a little late

### ISSUE THREAD

**Issue by vinod93** [pronebird/UIScrollView-InfiniteScroll#17] opened 2015-08-19 13:19 UTC
After fetching the data from server, when the new collection view items are inserted then the activity indicator hides late for 1 sec. 
What i want to do is to hide the activity indicator before the items are inserted, so inorder to resolve this what has to be done.

Thank you.

**Comment by pronebird** [comment] 2015-08-19 14:07
Hello! That does not sound right. Do you call `finishInfiniteScroll` from the main thread? Also I suggest you take a look at demo app which also uses collection view and everything seems to work fine.

**Comment by vinod93** [comment] 2015-08-19 19:38
Yes I did called it on main thread just like in the demo. The problem that I'm having is the activity indicator  stops animating almost 1sec later i.e., after the new items are inserted and on the call of the ```finish()``` block the ```finishInfiniteScroll``` method gets called & it take a delay.  
```
...
[self.collectionView insertItemsAtIndexPaths:arrayWithIndexPath];
}
 completion:^(BOOL finished) {
                        finish();
                    }]; 
```

So my concern here is how to solve this delaying issue.

**Comment by pronebird** [comment] 2015-08-19 20:11
Could you please prepare a sample project reproducing this issue?

**Comment by pronebird** [comment] 2015-08-20 09:02
Oh yeah, I think I see what you mean. It's in fact disappears with a short delay.

**Comment by vinod93** [comment] 2015-08-20 09:27
https://drive.google.com/file/d/0B3Q2nuVLZgySY3lOZlp0bDZMN0U/view?usp=sharing

You can have a look at the video demo. Also i'll tell you what I have changed from the demo code.

instead of 
```
    // Create custom indicator
CustomInfiniteIndicator *indicator = [[CustomInfiniteIndicator alloc] initWithFrame:CGRectMake(0, 0, 24, 24)]; 
```

I have created the default indicator 
```
UIActivityIndicatorView *indicator = [[UIActivityIndicatorView alloc]initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleGray];
```
and finally assigned it to this 
```
// Set custom indicator
    self.collectionView.infiniteScrollIndicatorView = indicator;
```

**Comment by vinod93** [comment] 2015-08-20 10:53
Yes so what can be done to correct that. Please.

**Comment by pronebird** [comment] 2015-10-05 12:54
Thanks for all suggestions and video that you recorded and sorry for a late reply. 

I know it does not look as good as it could be but I think there is not much to be done here. Apparently collection view delays the completion handler I assume to finish pending animations, that's why finishInfiniteScroll kicks in too late. I don't see how this issue can be solved with the public APIs that Apple provides us.

**Comment by doseAt** [comment] 2016-12-01 11:23
Hello prone bird. In the example project the animation of loading last about 5-6 seconds. The content in example project is very light, it should be pulled from server for max second or two, why it last so long?

**Comment by pronebird** [comment] 2016-12-01 12:51
@doseAt I don't think this issue is about that. In example project it's done for demo purposes. You can remove the delay.

**Comment by doseAt** [comment] 2016-12-01 14:19
@pronebird well i have a problem like that in my own project, loading bar keeps loading even after the pull from server is done and tableView.finishInfiniteScroll() is called. What can i try, and where can i find more docs about plugin?

**Comment by pronebird** [comment] 2016-12-01 14:21
@doseAt would you mind creating a separate issue and trying to create a minimal project to reproduce your issue? Most of the time the problem is that finishInfiniteScroll() is called on background thread.

**Comment by pronebird** [comment] 2016-12-01 15:06
@doseAt documentation is generated from source code and is available at http://cocoadocs.org/docsets/UIScrollView-InfiniteScroll/0.9.1/

**Comment by pronebird** [comment] 2018-03-04 17:15
Closing because there is not much can be done, `UICollectionView` calls `completionHandler` a little late. You may want to file a radar with Apple.

**Closed by pronebird** 2018-03-04 17:15 UTC
Labels: wontfix
